### ISSUE TITLE
Enhance fragments manifest description 

### ISSUE THREAD

**Issue by kavi87** [seedstack/w20#6]
Currently our fragments manifests have a description of configuration properties that are potentially very useful for a yeoman generator, but they are somehow too many and/or sometimes not very explicit for the end user. Adding some metadata targeted for the generator and enhancing the description would be a good thing.

**Comment by adrienlauer** [comment]
I agree. This could be very useful to get a good yeoman generation experience and this could scale to user defined fragments. They may potentially use the w20 generator with their own  fragments if possible.

But we should have a working yeoman generator in github first. @kavi87, could you consider to put the generator you already wrote on its own repository ? I will create the repo. You need to remove the automatic questions first since there are too many to be useful. Use sensible defaults for now (or nothing).

**Comment by kavi87** [comment]
Alright, I'll push the entire generator to my repo  then I'll create a branch for a basic generator in my own repo as well. Once ready I'll submit it as a pull request to the repo you'll create for it for seedstack.

**Comment by kavi87** [comment]
You can test the basic generator from my repo ([master](https://github.com/kavi87/generator-w20))
